/*
 * conf_device.h
 *
 * Created: 2014/3/14 19:48:26
 *  Author: Airj
 */ 


#ifndef CONF_DEVICE_H_
#define CONF_DEVICE_H_


#define DEVICE_KEY_POWER IOPORT_CREATE_PIN(PORTE, 2)
#define DEVICE_KEY_SELECT IOPORT_CREATE_PIN(PORTE, 3)
#define DEVICE_KEY_MODE IOPORT_CREATE_PIN(PORTD, 7)

#define DEVICE_LASER_ENABLE IOPORT_CREATE_PIN(PORTR, 0)

#define DEVICE_FAN_ENABLE IOPORT_CREATE_PIN(PORTD, 1)

#define DEVICE_VCC_12V_POWER_ENABLE IOPORT_CREATE_PIN(PORTD,5)

#define DEVICE_AVCC_3V_POWER_ENABLE IOPORT_CREATE_PIN(PORTD,6)

#define DEVICE_ANALOG_ENABLE IOPORT_CREATE_PIN(PORTD, 6)



#endif /* CONF_DEVICE_H_ */